// Datos del set Base (base1) del Pokémon TCG — 102 cartas.
// Nombres, números y rarezas son datos públicos del set físico (1999).
// Las imágenes se sirven desde el CDN público de pokemontcg.io.
export const BASE1_CARDS = [
  ["1", "Alakazam", "Rare Holo"],
  ["2", "Blastoise", "Rare Holo"],
  ["3", "Chansey", "Rare Holo"],
  ["4", "Charizard", "Rare Holo"],
  ["5", "Clefairy", "Rare Holo"],
  ["6", "Gyarados", "Rare Holo"],
  ["7", "Hitmonchan", "Rare Holo"],
  ["8", "Machamp", "Rare Holo"],
  ["9", "Magneton", "Rare Holo"],
  ["10", "Mewtwo", "Rare Holo"],
  ["11", "Nidoking", "Rare Holo"],
  ["12", "Ninetales", "Rare Holo"],
  ["13", "Poliwrath", "Rare Holo"],
  ["14", "Raichu", "Rare Holo"],
  ["15", "Venusaur", "Rare Holo"],
  ["16", "Zapdos", "Rare Holo"],
  ["17", "Beedrill", "Rare"],
  ["18", "Dragonair", "Rare"],
  ["19", "Dugtrio", "Rare"],
  ["20", "Electabuzz", "Rare"],
  ["21", "Electrode", "Rare"],
  ["22", "Pidgeotto", "Rare"],
  ["23", "Arcanine", "Rare"],
  ["24", "Charmeleon", "Uncommon"],
  ["25", "Dewgong", "Uncommon"],
  ["26", "Dratini", "Uncommon"],
  ["27", "Farfetch'd", "Uncommon"],
  ["28", "Growlithe", "Uncommon"],
  ["29", "Haunter", "Uncommon"],
  ["30", "Ivysaur", "Uncommon"],
  ["31", "Jynx", "Uncommon"],
  ["32", "Kadabra", "Uncommon"],
  ["33", "Kakuna", "Uncommon"],
  ["34", "Machoke", "Uncommon"],
  ["35", "Magikarp", "Uncommon"],
  ["36", "Magmar", "Uncommon"],
  ["37", "Nidorino", "Uncommon"],
  ["38", "Poliwhirl", "Uncommon"],
  ["39", "Porygon", "Uncommon"],
  ["40", "Raticate", "Uncommon"],
  ["41", "Seel", "Uncommon"],
  ["42", "Wartortle", "Uncommon"],
  ["43", "Abra", "Common"],
  ["44", "Bulbasaur", "Common"],
  ["45", "Caterpie", "Common"],
  ["46", "Charmander", "Common"],
  ["47", "Clefairy", "Common"],
  ["48", "Diglett", "Common"],
  ["49", "Doduo", "Common"],
  ["50", "Drowzee", "Common"],
  ["51", "Gastly", "Common"],
  ["52", "Koffing", "Common"],
  ["53", "Machop", "Common"],
  ["54", "Magnemite", "Common"],
  ["55", "Metapod", "Common"],
  ["56", "Nidoran female", "Common"],
  ["57", "Nidoran male", "Common"],
  ["58", "Onix", "Common"],
  ["59", "Pidgey", "Common"],
  ["60", "Pikachu", "Common"],
  ["61", "Poliwag", "Common"],
  ["62", "Ponyta", "Common"],
  ["63", "Rattata", "Common"],
  ["64", "Sandshrew", "Common"],
  ["65", "Squirtle", "Common"],
  ["66", "Starmie", "Common"],
  ["67", "Staryu", "Common"],
  ["68", "Tangela", "Common"],
  ["69", "Voltorb", "Common"],
  ["70", "Vulpix", "Common"],
  ["71", "Weedle", "Common"],
  ["72", "Clefairy Doll", "Uncommon"],
  ["73", "Computer Search", "Rare"],
  ["74", "Devolution Spray", "Uncommon"],
  ["75", "Impostor Professor Oak", "Uncommon"],
  ["76", "Item Finder", "Uncommon"],
  ["77", "Lass", "Uncommon"],
  ["78", "Pokémon Breeder", "Rare"],
  ["79", "Pokémon Trader", "Rare"],
  ["80", "Scoop Up", "Uncommon"],
  ["81", "Super Energy Removal", "Uncommon"],
  ["82", "Defender", "Uncommon"],
  ["83", "Energy Retrieval", "Common"],
  ["84", "Full Heal", "Common"],
  ["85", "Maintenance", "Common"],
  ["86", "PlusPower", "Common"],
  ["87", "Pokémon Center", "Common"],
  ["88", "Pokédex", "Common"],
  ["89", "Professor Oak", "Common"],
  ["90", "Revive", "Common"],
  ["91", "Super Potion", "Common"],
  ["92", "Bill", "Common"],
  ["93", "Energy Removal", "Common"],
  ["94", "Gust of Wind", "Common"],
  ["95", "Potion", "Common"],
  ["96", "Switch", "Common"],
  ["97", "Clefairy", "Common"],
  ["98", "Double Colorless Energy", "Uncommon"],
  ["99", "Fighting Energy", "Common"],
  ["100", "Fire Energy", "Common"],
  ["101", "Grass Energy", "Common"],
  ["102", "Water Energy", "Common"],
];
