// Datos del set Base (base1) del Pokémon TCG — 102 cartas.
// Nombres, números y rarezas son datos públicos del set físico (1999).
// Las imágenes se sirven desde el CDN público de pokemontcg.io.
export const BASE1_CARDS = [
  ["1", "Alakazam", "Rare Holo"],
  ["2", "Blastoise", "Rare Holo"],
  ["3", "Chansey", "Rare Holo"],
  ["4", "Charizard", "Rare Holo"],
  ["5", "Clefairy", "Rare Holo"],
  ["6", "Gyarados", "Rare Holo"],
  ["7", "Hitmonchan", "Rare Holo"],
  ["8", "Machamp", "Rare Holo"],
  ["9", "Magneton", "Rare Holo"],
  ["10", "Mewtwo", "Rare Holo"],
  ["11", "Nidoking", "Rare Holo"],
  ["12", "Ninetales", "Rare Holo"],
  ["13", "Poliwrath", "Rare Holo"],
  ["14", "Raichu", "Rare Holo"],
  ["15", "Venusaur", "Rare Holo"],
  ["16", "Zapdos", "Rare Holo"],
  ["17", "Beedrill", "Rare"],
  ["18", "Dragonair", "Rare"],
  ["19", "Dugtrio", "Rare"],
  ["20", "Electabuzz", "Rare"],
  ["21", "Electrode", "Rare"],
  ["22", "Pidgeotto", "Rare"],
  ["23", "Arcanine", "Uncommon"],
  ["24", "Charmeleon", "Uncommon"],
  ["25", "Dewgong", "Uncommon"],
  ["26", "Dratini", "Uncommon"],
  ["27", "Farfetch'd", "Uncommon"],
  ["28", "Growlithe", "Uncommon"],
  ["29", "Haunter", "Uncommon"],
  ["30", "Ivysaur", "Uncommon"],
  ["31", "Jynx", "Uncommon"],
  ["32", "Kadabra", "Uncommon"],
  ["33", "Kakuna", "Uncommon"],
  ["34", "Machoke", "Uncommon"],
  ["35", "Magikarp", "Uncommon"],
  ["36", "Magmar", "Uncommon"],
  ["37", "Nidorino", "Uncommon"],
  ["38", "Poliwhirl", "Uncommon"],
  ["39", "Porygon", "Uncommon"],
  ["40", "Raticate", "Uncommon"],
  ["41", "Seel", "Uncommon"],
  ["42", "Wartortle", "Uncommon"],
  ["43", "Abra", "Common"],
  ["44", "Bulbasaur", "Common"],
  ["45", "Caterpie", "Common"],
  ["46", "Charmander", "Common"],
  ["47", "Diglett", "Common"],
  ["48", "Doduo", "Common"],
  ["49", "Drowzee", "Common"],
  ["50", "Gastly", "Common"],
  ["51", "Koffing", "Common"],
  ["52", "Machop", "Common"],
  ["53", "Magnemite", "Common"],
  ["54", "Metapod", "Common"],
  ["55", "Nidoran (m)", "Common"],
  ["56", "Onix", "Common"],
  ["57", "Pidgey", "Common"],
  ["58", "Pikachu", "Common"],
  ["59", "Poliwag", "Common"],
  ["60", "Ponyta", "Common"],
  ["61", "Rattata", "Common"],
  ["62", "Sandshrew", "Common"],
  ["63", "Squirtle", "Common"],
  ["64", "Starmie", "Common"],
  ["65", "Staryu", "Common"],
  ["66", "Tangela", "Common"],
  ["67", "Voltorb", "Common"],
  ["68", "Vulpix", "Common"],
  ["69", "Weedle", "Common"],
  ["70", "Clefairy Doll", "Rare"],
  ["71", "Computer Search", "Rare"],
  ["72", "Devolution Spray", "Rare"],
  ["73", "Impostor Professor Oak", "Rare"],
  ["74", "Item Finder", "Rare"],
  ["75", "Lass", "Rare"],
  ["76", "Pokémon Breeder", "Rare"],
  ["77", "Pokémon Trader", "Rare"],
  ["78", "Scoop Up", "Rare"],
  ["79", "Super Energy Removal", "Rare"],
  ["80", "Defender", "Uncommon"],
  ["81", "Energy Retrieval", "Uncommon"],
  ["82", "Full Heal", "Uncommon"],
  ["83", "Maintenance", "Uncommon"],
  ["84", "PlusPower", "Uncommon"],
  ["85", "Pokémon Center", "Uncommon"],
  ["86", "Pokémon Flute", "Uncommon"],
  ["87", "Pokédex", "Uncommon"],
  ["88", "Professor Oak", "Uncommon"],
  ["89", "Revive", "Uncommon"],
  ["90", "Super Potion", "Uncommon"],
  ["91", "Bill", "Common"],
  ["92", "Energy Removal", "Common"],
  ["93", "Gust of Wind", "Common"],
  ["94", "Potion", "Common"],
  ["95", "Switch", "Common"],
  ["96", "Double Colorless Energy", "Uncommon"],
  ["97", "Fighting Energy", "Common"],
  ["98", "Fire Energy", "Common"],
  ["99", "Grass Energy", "Common"],
  ["100", "Lightning Energy", "Common"],
  ["101", "Psychic Energy", "Common"],
  ["102", "Water Energy", "Common"],
];